"""CLI for generating synthetic scenario splits and saving them as JSONL.

Usage::

    python3 -m reference_v2.synthetic.generate \\
        --train 8000 --dev 1000 --test 1000 --seed 42 \\
        --out experiments/data/synthetic_v1/

Each split is saved as ``{out}/train.jsonl``, ``{out}/dev.jsonl``, and
``{out}/test.jsonl``.  Every file contains one JSON object per line with
the following keys:

* ``scenario_id`` — unique string identifier (e.g. ``"scenario_00042"``)
* ``evidence_redundancy`` — int in ``{1, 2, 5, 10}`` (from split plan)
* ``corpus_sentences`` — list of ``{"text": str, "supports_query": bool}``
* ``planted_verdict`` — one of ``"SUPPORTS"``, ``"REFUTES"``, ``"NEI"``
* ``planted_thinness`` — int (count of sentences where supports_query is True)
* ``planted_hop_count`` — int (compositional depth / number of inference hops)

Evidence redundancy per scenario is assigned by ``make_splits()`` using
thinness-curriculum stratification over ``{1, 2, 5, 10}``.  Scenarios are
generated in groups by evidence_redundancy value to ensure that each scenario
gets the correct ``er`` while preserving full determinism.
"""

from __future__ import annotations

import argparse
import json
import time
from collections import defaultdict
from pathlib import Path

from reference_v2.synthetic.generator import Generator, Scenario
from reference_v2.synthetic.splits import make_splits

# Ordered list of curriculum strata — generation must iterate in this fixed
# order so that two runs with the same seed produce byte-identical output.
_CURRICULUM_STRATA: tuple[int, ...] = (1, 2, 5, 10)

_DEFAULT_COMPOSITIONAL_DEPTH = 2
_DEFAULT_CONTRADICTION_DENSITY = 0.33
_DEFAULT_NEI_FRACTION = 0.33


def _scenario_to_dict(
    scenario: Scenario,
    scenario_id: str,
    evidence_redundancy: int,
) -> dict:
    """Convert a Scenario dataclass to a JSON-serialisable dict.

    Args:
        scenario: The generated Scenario object.
        scenario_id: Unique identifier from the split plan.
        evidence_redundancy: The er value used to generate this scenario.

    Returns:
        A dict ready for JSON serialisation with all oracle labels and
        split-plan metadata.
    """
    return {
        "scenario_id": scenario_id,
        "evidence_redundancy": evidence_redundancy,
        "corpus_sentences": [
            {"text": s.text, "supports_query": s.supports_query}
            for s in scenario.corpus_sentences
        ],
        "planted_verdict": scenario.planted_verdict,
        "planted_thinness": scenario.planted_thinness,
        "planted_hop_count": scenario.planted_hop_count,
    }


def generate_and_save(
    train: int,
    dev: int,
    test: int,
    seed: int,
    out: Path,
    compositional_depth: int = _DEFAULT_COMPOSITIONAL_DEPTH,
    contradiction_density: float = _DEFAULT_CONTRADICTION_DENSITY,
    nei_fraction: float = _DEFAULT_NEI_FRACTION,
) -> None:
    """Generate scenarios with per-scenario evidence_redundancy, then write JSONL.

    Uses ``make_splits()`` to obtain a split plan that assigns each scenario an
    ``evidence_redundancy`` from ``{1, 2, 5, 10}`` via thinness-curriculum
    stratification.  Scenarios are generated by grouping on ``er`` so that the
    correct supporting-sentence count is planted in each scenario.

    Args:
        train: Number of training scenarios.
        dev: Number of development scenarios.
        test: Number of test scenarios.
        seed: Random seed for reproducibility.
        out: Output directory path.
        compositional_depth: Inference hops; stored as planted_hop_count.
        contradiction_density: Fraction of scenarios assigned REFUTES verdict.
        nei_fraction: Fraction of scenarios assigned NEI verdict.
    """
    total = train + dev + test
    out.mkdir(parents=True, exist_ok=True)

    print(
        f"Generating {total} scenarios "
        f"(train={train}, dev={dev}, test={test}, seed={seed}) ...",
        flush=True,
    )
    print(
        f"  compositional_depth={compositional_depth}, "
        f"contradiction_density={contradiction_density}, "
        f"nei_fraction={nei_fraction}",
        flush=True,
    )

    t0 = time.monotonic()

    # ── Step 1: Obtain split plan with per-scenario evidence_redundancy ──────
    splits = make_splits(seed=seed, train=train, dev=dev, test=test)

    # Flatten all scenarios from all splits, preserving split membership.
    # Each entry: (split_name, position_in_split, scenario_id, er)
    all_meta: list[tuple[str, int, str, int]] = []
    for split_name in ("train", "dev", "test"):
        for pos, meta in enumerate(splits[split_name]):
            all_meta.append((split_name, pos, meta["scenario_id"], meta["evidence_redundancy"]))

    # ── Step 2: Group scenario positions by evidence_redundancy ─────────────
    # Each er maps to a list of (split_name, pos, scenario_id) tuples,
    # in the order they appear across train/dev/test.  This order is fixed and
    # deterministic, so the sequential indexing into generated batches is stable.
    er_groups: dict[int, list[tuple[str, int, str]]] = defaultdict(list)
    for split_name, pos, scenario_id, er in all_meta:
        er_groups[er].append((split_name, pos, scenario_id))

    # ── Step 3: Generate one batch per er value in canonical stratum order ───
    # Using a shared Generator (same seed) and iterating strata in fixed order
    # ensures byte-identical output across runs.
    generator = Generator(seed=seed)

    # Slot matrix: generated Scenario objects keyed by (split_name, position).
    scenario_slots: dict[tuple[str, int], tuple[Scenario, str, int]] = {}

    for er in _CURRICULUM_STRATA:
        group = er_groups.get(er, [])
        if not group:
            continue
        n = len(group)
        batch: list[Scenario] = generator.generate(
            n_docs=n,
            evidence_redundancy=er,
            compositional_depth=compositional_depth,
            contradiction_density=contradiction_density,
            nei_fraction=nei_fraction,
        )
        # Map each generated scenario to its slot using sequential indexing.
        for batch_idx, (split_name, pos, scenario_id) in enumerate(group):
            scenario_slots[(split_name, pos)] = (batch[batch_idx], scenario_id, er)

    elapsed = time.monotonic() - t0
    rate = total / elapsed if elapsed > 0 else float("inf")
    print(
        f"Generated {total} scenarios in {elapsed:.3f}s ({rate:.1f} scenarios/sec)",
        flush=True,
    )

    # ── Step 4: Assemble splits and write JSONL files ────────────────────────
    split_sizes = {"train": train, "dev": dev, "test": test}

    for split_name in ("train", "dev", "test"):
        expected = split_sizes[split_name]
        records: list[dict] = []

        for pos in range(expected):
            scenario, scenario_id, er = scenario_slots[(split_name, pos)]
            records.append(_scenario_to_dict(scenario, scenario_id, er))

        assert len(records) == expected, (
            f"Expected {expected} records for {split_name}, got {len(records)}"
        )

        out_path = out / f"{split_name}.jsonl"
        with out_path.open("w", encoding="utf-8") as fh:
            for record in records:
                fh.write(json.dumps(record, separators=(",", ":")) + "\n")

        print(f"Wrote {len(records)} scenarios -> {out_path}", flush=True)

    total_elapsed = time.monotonic() - t0
    print(f"Total wall-clock time: {total_elapsed:.3f}s", flush=True)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate synthetic fact-checking scenario splits (JSONL output).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--train", type=int, required=True, help="Number of training scenarios."
    )
    parser.add_argument(
        "--dev", type=int, required=True, help="Number of development scenarios."
    )
    parser.add_argument(
        "--test", type=int, required=True, help="Number of test scenarios."
    )
    parser.add_argument(
        "--seed", type=int, default=42, help="Random seed for reproducibility."
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output directory for train.jsonl, dev.jsonl, test.jsonl.",
    )
    parser.add_argument(
        "--compositional-depth",
        type=int,
        default=_DEFAULT_COMPOSITIONAL_DEPTH,
        help="Number of inference hops (planted_hop_count).",
    )
    parser.add_argument(
        "--contradiction-density",
        type=float,
        default=_DEFAULT_CONTRADICTION_DENSITY,
        help="Fraction of scenarios assigned REFUTES verdict.",
    )
    parser.add_argument(
        "--nei-fraction",
        type=float,
        default=_DEFAULT_NEI_FRACTION,
        help="Fraction of scenarios assigned NEI verdict.",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    """Entry point for the CLI module."""
    parser = _build_parser()
    args = parser.parse_args(argv)

    generate_and_save(
        train=args.train,
        dev=args.dev,
        test=args.test,
        seed=args.seed,
        out=args.out,
        compositional_depth=args.compositional_depth,
        contradiction_density=args.contradiction_density,
        nei_fraction=args.nei_fraction,
    )


if __name__ == "__main__":
    main()
